import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Sidebar from "@/components/sidebar";
import Header from "@/components/header";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} flex items-start justify-between`}>
        <div className="hidden lg:flex min-w-[300px]">
        <Sidebar/>
        </div>
        <main className="mb-5 w-full h-full">
          <Header/>
          <div className="p-5">
            {children}
          </div>
        </main>
      </body>
    </html>
  );
}
